[Schedule management app] make cell edit&delete
DONOTINTO/ScheduleManagementApp pull request #6
Opened 2023-03-28 12:05 UTC by DONOTINTO

- 테이블 뷰 셀 오른쪽 스와이프 기능 추가
- edit, delete 버튼 추가
- delete 클릭 시 데이터 삭제 및 테이블 셀 삭제

2023-03-28 17:21 UTC, keenkim1202 requested changes
전반적으로 잘 작성했습니다! 수정사항 수정 후 코멘트 남겨주세요~
@DONOTINTO

2023-03-28 17:21 UTC, keenkim1202 commented on ScheduleManagementApp/ScheduleManagementApp/Controller/HomeViewController.swift
> +        let editButton = UIContextualAction(style: .normal, title: "수정") { (action, view, completionHandler) in
`action`, `view`, `completionHandler` 중 사용하지 않는 것은 `_` 표시로 수정해주세요!
만약 모두 사용하지 않는다면 `_, _, _` 로 작성하시면 됩니다.

2023-03-28 17:21 UTC, keenkim1202 commented on ScheduleManagementApp/ScheduleManagementApp/Controller/HomeViewController.swift
> +        let deleteButton = UIContextualAction(style: .normal, title: "삭제") { (action, view, completionHandler) in
여기도 사용하지 않는 것은 `_` 표시로 수정해주세요!

2023-03-28 17:21 UTC, keenkim1202 commented on ScheduleManagementApp/ScheduleManagementApp/Model/ScheduleManager.swift
> +        let index = indexPath.row
```suggestion
        let schedule = scheduleList[indexPath.row]
        schedule.title = title
```

2023-03-28 17:21 UTC, keenkim1202 commented on ScheduleManagementApp/ScheduleManagementApp/View/DatePickerView.swift
>          titleLabel.font = .systemFont(ofSize: 15, weight: .medium)
font도 CustomFont 구조체를 만들어 사용하면 어떨까요?
같은 폰트 형식 몇가지를 여기저기서 사용하는 것으로 보여집니다ㅎㅎ

2023-03-29 14:05 UTC, DONOTINTO commented on ScheduleManagementApp/ScheduleManagementApp/Model/ScheduleManager.swift
> +        let index = indexPath.row
@keenkim1202 Schedule 자체는 struct (값) 타입이라 위와 같이 하면 데이터 저장이 안되는데, class로 바꿀까요?

2023-03-29 14:10 UTC, DONOTINTO commented on ScheduleManagementApp/ScheduleManagementApp/View/DatePickerView.swift
>          titleLabel.font = .systemFont(ofSize: 15, weight: .medium)
@keenkim1202 여기까지 수정 완료했습니다!

2023-04-03 05:44 UTC, merged

2023-04-03 05:48 UTC, keenkim1202 commented on ScheduleManagementApp/ScheduleManagementApp/Model/ScheduleManager.swift
> +        let index = indexPath.row
@DONOTINTO 밀린 PR이 많아서 이부분은 다음 PR에서 수정하는 방향으로 합시다!
값타입이어도 응용하면 아래와 같이 코드를 작성해줄 수 있습니다ㅎㅎ
모델을 만들어주었기에 새로운 값으로 구성된 인스턴스를 생성해주고 대입해줄 수 있습니다.
```swift
        let newSchedule = Schedule(title: title, allDay: allDay, startDate: startDate, endDate: endDate)
        scheduleList[indexPath.row] = newSchedule
```