[Schedule management app] calendar view 생성 및 기본 설정
DONOTINTO/ScheduleManagementApp pull request #7
Opened 2023-03-31 11:43 UTC by DONOTINTO

- calendarVC 생성
- calendarView 생성
- calendarVC의 mainView를 calendarView로 설정
- calendar View 레이아웃 및 UI 설정

2023-04-03 06:35 UTC, keenkim1202 requested changes
@DONOTINTO 
(추천) 은 필수로 수정하진 않아도 되며 어느정도는 개인의 취향의 영역에 속하는 내용입니다.
하지만 추천할 것을 권고드리는 내용이니 참고해보시길 바랍니다!

2023-04-03 06:35 UTC, keenkim1202 commented on ScheduleManagementApp/ScheduleManagementApp/Controller/DetailViewController.swift
> +    private var cellIndex: IndexPath?
`section` 정보도 사용하나요?
만약 향후에 `row` 정보만 사용할 예정이라면 `Int`값만 받아도 좋을 것 같습니다~!

2023-04-03 06:35 UTC, keenkim1202 commented on ScheduleManagementApp/ScheduleManagementApp/Controller/DetailViewController.swift
> +    private var cellIndex: IndexPath?
향후 section 정보를 활용할 예정이라면 그대로 유지해도 괜찮습니다.

2023-04-03 06:35 UTC, keenkim1202 commented on ScheduleManagementApp/ScheduleManagementApp/Controller/DetailViewController.swift
>      // MARK: - shouldChangeCharactersIn
(추천) 함수마다 MARK 를 표시하지 않아도 됩니다.
extension이나 class, 혹은 class 내부가 매우 길 때 영역을 구분하기 위해서 사용하곤 합니다.

2023-04-03 06:35 UTC, keenkim1202 commented on ScheduleManagementApp/ScheduleManagementApp/Model/ScheduleManager.swift
> +    // MARK: - edit
(추천) 여기도 마찬가지로 함수마다 MARK 를 할 필요는 없습니다.
오히려 너무 많은 MARK는 지저분해 보일 수 있습니다!

2023-04-03 06:35 UTC, keenkim1202 commented on ScheduleManagementApp/ScheduleManagementApp/UIKit+/UIViewController+.swift
> +    // 화면 어느 곳을 터치하든 키보드 내리기
```suggestion
    /// 화면 어느 곳을 터치하든 키보드 내리기
```
슬래시를 3개 작성해야 함수를 사용한 위치에서 함수의 summary를 볼 수 있습니다.

2023-04-03 06:35 UTC, keenkim1202 commented on ScheduleManagementApp/ScheduleManagementApp/View/CalendarView.swift
> +        calendar.calendarWeekdayView.weekdayLabels[0].text = "일"
```suggestion
        let dayOfTheWeek = ["일", "월", "화", "수", "목", "금", "토"]
        for i in 0..<dayOfTheWeek.count {
            calendar.calendarWeekdayView.weekdayLabels[i].text = dayOfTheWeek[i]
        }
```

2023-04-03 06:35 UTC, keenkim1202 commented on ScheduleManagementApp/ScheduleManagementApp/View/CalendarView.swift
> +        calendar.snp.makeConstraints {
```suggestion
        calendar.snp.makeConstraints {
            $0.edges.equalTo(self.snp.edges)
        }
```

2023-04-03 06:35 UTC, keenkim1202 commented on ScheduleManagementApp/ScheduleManagementApp/View/DetailView.swift
> +        initialTextField(titleTextField, placeholder: "타이틀을 입력하세요", title: nil)
`initialTextField()` 함수 선언부에 기본값을 추가해서 불필요한 인자는 작성할 필요가 없도록 해보세요~!

2023-04-03 06:35 UTC, keenkim1202 commented on ScheduleManagementApp/ScheduleManagementApp/View/DetailView.swift
> +        allDayLabel.textColor = .black
allday 여부에 대해서도 `enum`을 만들어 관리해도 좋을 것 같습니다.

2023-04-03 06:35 UTC, keenkim1202 commented on ScheduleManagementApp/ScheduleManagementApp/View/DetailView.swift
> +        // 뒤로가기 버튼
너무 많은 주석과 공백으로 인해 함수의 길이가 거의 두배가 되고 있습니다.
코드를 보고 알 수 있는 내용은 주석을 작성하지 않고
꼭 필요한 경우만 짧고 간결하게 작성하는 방식으로 수정하기를 추천드립니다.

2023-04-03 12:46 UTC, DONOTINTO commented on ScheduleManagementApp/ScheduleManagementApp/View/DetailView.swift
> +        allDayLabel.textColor = .black
@keenkim1202 해당 부분만 제외하고 모두 수정 완료했습니다

2023-04-05 08:17 UTC, keenkim1202 commented on ScheduleManagementApp/ScheduleManagementApp/View/DetailView.swift
> +        allDayLabel.textColor = .black
@DONOTINTO 수정된 커밋 이 어떤건가요? 링크 부탁드립니다

2023-04-05 08:20 UTC, keenkim1202 commented on ScheduleManagementApp/ScheduleManagementApp/View/DetailView.swift
> +        allDayLabel.textColor = .black
[[update] ConstColor 변수명 변경 (UIColor)](https://github.com/DONOTINTO/ScheduleManagementApp/pull/8/commits/717cdce6b2ce2e3ac1950d5b0fbc829206c3ba3d)

여기에 한건가요? 다른 브랜치에 수정하신것 같습니다~

2023-04-05 08:27 UTC, keenkim1202 commented
https://github.com/DONOTINTO/ScheduleManagementApp/pull/8

위의 PR에서 수정사항 확인 완료하였습니다.

2023-04-05 09:32 UTC, merged